config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    member do
      patch 'update_pomodoro_count'
    end
  end

  devise_for :users
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Pomodebtor
  </small>
  <nav>
    <ul class="nav nav-pills pull-right">
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
	  
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <%= link_to "pomodebtor", root_path, id: "logo" %>
    <nav>
	  <ul class="nav nav-pills pull-right">	  
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        
        
        <% if user_signed_in? %>
		  <li><%= link_to "Courses", courses_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_keenchart.html.erb
<script type="text/javascript">
  !function(a,b){a("Keen","https://d26b395fwzu5fz.cloudfront.net/3.2.3/keen.min.js",b)}(function(a,b,c){var d,e,f;c["_"+a]={},c[a]=function(b){c["_"+a].clients=c["_"+a].clients||{},c["_"+a].clients[b.projectId]=this,this._config=b},c[a].ready=function(b){c["_"+a].ready=c["_"+a].ready||[],c["_"+a].ready.push(b)},d=["addEvent","setGlobalProperties","trackExternalLink","on"];for(var g=0;g<d.length;g++){var h=d[g],i=function(a){return function(){return this["_"+a]=this["_"+a]||[],this["_"+a].push(arguments),this}};c[a].prototype[h]=i(h)}e=document.createElement("script"),e.async=!0,e.src=b,f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(e,f)},this);
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
	<%= render 'layouts/keenchart'%>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
		
	  <% flash.each do |key, value| %>
	  	 <div class="alert alert-<%= key %>"><%= value %></div>
	  <% end %>	
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>